### ISSUE TITLE
No way to reprompt facebook login permissions.

### ISSUE THREAD

**Issue by mason-bially** [mfkp/tinderplusplus#11]
With the new facebook login system you have to reprompt for permissions to reset the app permissions. I'm not sure if this can be done with tinder++, but here is the [facebook dev post](https://developers.facebook.com/blog/post/2014/04/30/the-new-facebook-login), and the [specific documentation](https://developers.facebook.com/docs/facebook-login/login-flow-for-web/v2.2#re-asking-declined-permissions).

I would implement this myself and submit the pull request but this is way outside my bailiwick I wouldn't even know where to begin. I'm namely looking for a (small) link (maybe underneath sign in with facebook?) which says something like "Reprompt for App Permissions".

**Comment by mfkp** [comment]
Hi @mason-bially, not sure I'm totally understanding the problem. Why do you need to re-request the app permissions? Are you having troubles logging in?

**Comment by mason-bially** [comment]
You're right, I figured it out by editing the URL in the login window.
