### ISSUE TITLE
Long conversations do not show

### ISSUE THREAD

**Issue by acence** [mfkp/tinderplusplus#17]
When i click through the conversations, sometimes, if i have a longer conversation, it will not load, and the conversation from the previous person will remain.

The name on top changes fine

Issue spotted on windows 7 & 8
![1](https://cloud.githubusercontent.com/assets/3876211/9632415/56f95482-5187-11e5-8ed5-8afaca03ceef.PNG)
![2](https://cloud.githubusercontent.com/assets/3876211/9632416/56fbdfcc-5187-11e5-9bcc-d270b7613dfb.PNG)

**Comment by mfkp** [comment]
Interesting, thanks for reporting - I'll take a look next time I'm working on messages.

Question - if you click to a different conversation and back to this one, does it load the right conversation? Or does it always load the wrong one?

**Comment by acence** [comment]
If you go to a third conversation, it will load fine, and when you return to the broken one, the third one will remain. 
My guess is the messages loading fails, and it never gets replaced. No error info either

**Comment by cjthompson** [comment]
Should be fixed by PR #19 .

**Comment by mfkp** [comment]
Thanks @cjthompson
