### ISSUE TITLE
Linux build?

### ISSUE THREAD

**Issue by richmito** [mfkp/tinderplusplus#20]
I tried this
$ sudo npm install
[sudo] password for rich: 
npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your operating system or architecture: appdmg@0.3.4
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/rich/prog/tinderpp/tinderplusplus
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code EBADPLATFORM
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/rich/prog/tinderpp/tinderplusplus/npm-debug.log
npm ERR! not ok code 0

Debian 8 x86_64
Node v0.10.29
nw.js v0.12.3

:(

**Comment by mfkp** [comment]
Yeah, that's a mac-specific tool for building the mac installer - you don't need that.

To run on Linux, just run the `npm install` command inside the desktop-app directory, then you should be able to run it as instructed in the Readme.

**Comment by richmito** [comment]
Worked :D
/opt/nwjs/nw ~/prog/tinderplusplus/desktop-app

i will make a *.desktop file to this, maybe a package to easy use

**Comment by mfkp** [comment]
:+1:
