### ISSUE TITLE
Profile pictures not updated

### ISSUE THREAD

**Issue by Timoses** [mfkp/tinderplusplus#23]
I realised that only the profile pictures are uploaded to the Tinder++. However, upon changing the profile pictures on the facebook profile no changes occur in the Tinder++ app.

I can't even seem to redo the process of setting up Tinder++ since it seems to simply store the 'session'. So I'm lost with a useless Tinder++ profile. Digged a bit in the code, but I'm not proficient with javascript..

BTW I'm on OSX.

**Comment by mfkp** [comment]
The app currently doesn't support changing your profile photos and bio, so that part you'll have to do on the official mobile phone app, then you should see the updated profile on the desktop app.
