### ISSUE TITLE
Tinder++ stuck at "loading" after first log in... on Mac

### ISSUE THREAD

**Issue by izalixe** [mfkp/tinderplusplus#26]
Help! I installed Tinder++ on my Macbook air, logged in with Facebook and it says Loading and had said that for hours , nothing is happening.... help ?

I also tried downloading Tinder on my phone and it just kept Downloading forever.

Karma doesnt want me to use Tinder or what ???

PLEASE HELP I am very new at this I usually dont use apps or smartphones.... thanks

**Comment by mfkp** [comment]
Hi there, generally you'll need to log in on the smartphone first to get your account set up. If you haven't set up your account, Tinder++ will not work.

**Comment by izalixe** [comment]
Thanks so much for answering me. The thing is, I could NEVER succeded in
downloading the Tinder app on my phone !!! It keeps downloading &
downloading forever....

What do I do ?

*Iza*
*_______________________________*
*Visitez ** Izalixe Straightheart Écrivaine
<https://www.facebook.com/izalixe/info> *

2015-10-24 15:54 GMT-04:00 Kyle Powers <notifications@github.com>:

**Comment by izalixe** [comment]
I wrote to Tinder help and they gave me the download page link, so I went there and the Tinder app got download to my iTunes, in my COMPUTER..... now how do I move it from the computer to the phone ? By Bluetooth ? 

Otherwise as I said when I use Google Play on the phone, it never ends installing :/

I dont know much about computers at all
my phone is a LG-E450B  I dont know which iOs or Androit number it is ? I'm not computer savvy....

I appreciate any help you can give me
I'm actually trying to find people in another sexy to help me find someone I care about who's gonna be there at Xmas, this is not even for booty calls or dates.....
THANKS Kyle
Iza from Québec

**Comment by mfkp** [comment]
If you have an android device, you can install from the "Play Store" app on the phone.

If you have an apple device, search for tinder and install from the App Store on your phone.

You'll also need a Facebook account to log into the Tinder app once it's on the phone.

**Comment by izalixe** [comment]
As I said, I TRIED ALREADY installing from Google Play....
It says it's installing but then keeps loading forever..... ?

*Iza*
*_______________________________*
*Visitez ** Izalixe Straightheart Écrivaine
<https://www.facebook.com/izalixe/info> *

2015-10-25 23:56 GMT-04:00 Kyle Powers <notifications@github.com>:

**Comment by izalixe** [comment]
Can you tell me excatly how to find the latest version of Tinder on Google
Play ? It's so confusing, there are hundreds of apps... I basically
searched for Tinder, clicked on it, Install..... but then it just keep
loading forever....

The Tinder people told me I had to get the latest version for Android 4.3.5
 but it does not say 4.3.5 anywhere, I even searched it.... ?

*Iza*
*_______________________________*
*Visitez ** Izalixe Straightheart Écrivaine
<https://www.facebook.com/izalixe/info> *

2015-10-26 0:37 GMT-04:00 izalixe . <izalixe@gmail.com>:

**Comment by izalixe** [comment]
and again thank you SO MUCH for helping me

*Iza*
*_______________________________*
*Visitez ** Izalixe Straightheart Écrivaine
<https://www.facebook.com/izalixe/info> *

2015-10-26 0:39 GMT-04:00 izalixe . <izalixe@gmail.com>:

**Comment by izalixe** [comment]
Hm.... I tried to download another app as a test (Scrabble) and it does the
same.... do you think maybe there is not enough SPACE on my phone ? I do
have a lot of photos and videos....  how much space do you think Tinder
needs on a phone ? I have 709 Mo available ?

*Iza*
*_______________________________*
*Visitez ** Izalixe Straightheart Écrivaine
<https://www.facebook.com/izalixe/info> *

2015-10-26 0:40 GMT-04:00 izalixe . <izalixe@gmail.com>:

**Comment by mfkp** [comment]
Should be plenty of space. Sounds like an issue with your phone though if you can't install any apps. Try resetting the phone if you have to, unfortunately I can't help much with that.

Anyway, closing this issue since it's not related to the Tinder++ app.
