### ISSUE TITLE
New compiled version?

### ISSUE THREAD

**Issue by SaturnusDJ** [mfkp/tinderplusplus#34]
There is some addon code available here I guess, but is there also a complete, instant ready to use version like http://tinderplusplus.com ?

I think there is a bug in the download from above now because some new matches don't show up anymore.

**Comment by mrmayfield** [comment]
@SaturnusDJ Did you ever fix this bug?

**Comment by SaturnusDJ** [comment]
Not fixed, but also didn't happen again.

**Comment by mrmayfield** [comment]
Sounds good

**Comment by SaturnusDJ** [comment]
People who are interested, look here:
https://github.com/SaturnusDJ/tinderplusplus/tree/master/1_Ready_to_use_versions
https://github.com/SaturnusDJ/tinderplusplus/tree/unstable/1_Ready_to_use_versions

These are available to cover the time tinderjs/tinder-desktop needs to release the first compiled version.

**Comment by SaturnusDJ** [comment]
### Above post is outdated.
Read here for info: https://github.com/tinderjs/tinder-desktop/issues/5
From there full compiled versions are available.
