### ISSUE TITLE
Help! Can Not login tinderplusplus as of August 10th 2016

### ISSUE THREAD

**Issue by veryexoticdancer** [mfkp/tinderplusplus#45]
First It said:
You are not logged in: You are not logged in. Please log in and try again.

Then when I successfully tried to login in my facebook, it said
"URL Blocked: This redirect failed because the redirect URI is not whitelisted in the app’s Client OAuth Settings. Make sure Client and Web OAuth Login are on and add all your app domains as Valid OAuth Redirect URIs." I got this message when trying to login facebook from tinderplusplus windows on windows 8.1

please update the app so it can login facebook, without logging in facebook this app can not be working properly.

**Comment by aceangel3k** [comment]
OAuth isn't working for me as well.

**Comment by mrmayfield** [comment]
Hey guys, we're still actively maintaining this project at https://github.com/tinderjs/tinder-desktop. We've got a fix out for this that should be up within the day.

**Comment by aceangel3k** [comment]
Thanks mrmayfield.

**Comment by veryexoticdancer** [comment]
@mrmayfield thanks I guess I will use that instead!

**Comment by mfkp** [comment]
@veryexoticdancer @aceangel3k I just released a fix for the login issue. If you re-launch the app, it will auto-update after a few seconds, or you can download the new version from [tinderplusplus.com](http://tinderplusplus.com).
